### ISSUE TITLE
Credenciales de subdominio

### ISSUE THREAD

**Issue by Ontiveroshtml** [Ontiveroshtml/ontiveros_parcial_2-#3]
¿Me puede mandar las credenciales para el subdominio, por favor?

**Comment by ingreyeslara** [comment]
cual sería el nombre de su subdominio?

**Comment by Ontiveroshtml** [comment]
@ingreyeslara Abarrotesmisa

**Comment by ingreyeslara** [comment]
listo
![aba](https://github.com/user-attachments/assets/c0919082-b3cf-4bdd-b419-392b5699b4be)
![aba2](https://github.com/user-attachments/assets/f36083d2-ee3d-4503-a527-b9282defa7e7)

**Comment by Ontiveroshtml** [comment]
@ingreyeslara Que tal profe, al conectarme en el filezilla me sale error



![Image](https://github.com/user-attachments/assets/b6e48350-5912-4e8f-a437-5e5a170d6d28)

**Comment by ingreyeslara** [comment]
Está ingresando mal el usuario , por es no se puede conectar
